### PR TITLE
WIP: Custom Price Watch Interval

### PR DESCRIPTION
**Pull request by ernest-rudnicki**
Introduce two new commands `!statsInterval` and `!priceInterval` to change the default interval for posting statistics and current rate of Safemoon

### CODE REVIEW

**Comment by imfromthebay** [comment]
this adds a ton of useful features, would be super great to see it merged.

**Comment by reecebenson** [comment]
Hi @Terminatt,

Is there any chance of pointing this towards my open PR instead of the main branch?

Just to avoid commit confusion!

Cheers

**Comment by reecebenson** [comment]
> this adds a ton of useful features, would be super great to see it merged.

The changes here are from #18

**Comment by ernest-rudnicki** [comment]
@reecebenson sure. It seems I need to close this PR, and create new one. I am gonna do it right after work

**Comment by reecebenson** [comment]
> @reecebenson sure. It seems I need to close this PR, and create new one. I am gonna do it right after work

No problem, sorry to be annoying! It'll just keep the commit history tidier and I seem to be coordinating with Hank when bot updates are required so it'll streamline the process, hopefully! Looking forward to seeing your contributions.

**Comment by reecebenson** [comment]
On the above note, please make sure commits are labelled with `chore` / `feat` / `bugfix`, etc. See [the commit history](https://github.com/Safemoon-Protocol/Discord-Bot/commits/main) of the repository to get a bit more of an insight as to how we seem to be doing this, as in the meantime there are no rules set up but I'll get there eventually 😂 

`chore` - a commit that contains some clean up or non-feature related changes
`bugfix` - a commit that contains a bugfix for a previous commit on your branch or in the upstream
`feat` - a new feature addition to the source

**Pull request closed without merging**
